websiteNISHACK/urls.py
from django.contrib import admin
from django.urls import path
from webapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('test/', views.test, name='test'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('payment/', views.payment, name='payment'),
    path('send_friend_request/<str:username>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:friendship_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('friends/', views.friends, name='friends_list'),
    path('satmath/', views.satmath, name='satmath'),
    path('satverbal/', views.satverbal, name='satverbal'),
    path('store/', views.store, name='store'),
    path('satverbaltest1', views.satverbaltest1, name='satverbaltest1'),
    path('satverbaltest2', views.satverbaltest2, name='satverbaltest2'),
    path('satmathtest1', views.satmathtest1, name='satmathtest1'),

#authentication
    path('signup/', views.signupsystem, name='signupsystem'),
    path('', views.loginsystem, name='loginsystem'),
    path('logout/', views.logoutsystem, name='logoutsystem'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class Questions(models.Model):
    number = models.IntegerField(null=True)
    paragraph = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    question = models.CharField(max_length=500, null=True)
    answer1 = models.CharField(max_length=200, null=True)
    answer2 = models.CharField(max_length=200, null=True)
    answer3 = models.CharField(max_length=200, null=True)
    answer4 = models.CharField(max_length=200, null=True)
    correct = models.CharField(max_length=2)
    explanation = models.TextField()

class QuestionsVerbal1(models.Model):
    number = models.IntegerField(null=True)
    paragraph = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    question = models.CharField(max_length=500, null=True)
    answer1 = models.CharField(max_length=200, null=True)
    answer2 = models.CharField(max_length=200, null=True)
    answer3 = models.CharField(max_length=200, null=True)
    answer4 = models.CharField(max_length=200, null=True)
    correct = models.CharField(max_length=2)
    explanation = models.TextField(null=True, blank=True)

class QuestionsVerbal2(models.Model):
    number = models.IntegerField(null=True)
    paragraph = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    question = models.CharField(max_length=500, null=True)
    answer1 = models.CharField(max_length=200, null=True)
    answer2 = models.CharField(max_length=200, null=True)
    answer3 = models.CharField(max_length=200, null=True)
    answer4 = models.CharField(max_length=200, null=True)
    correct = models.CharField(max_length=2)
    explanation = models.TextField(null=True, blank=True)

class QuestionsVerbal3(models.Model):
    number = models.IntegerField(null=True)
    paragraph = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    question = models.CharField(max_length=500, null=True)
    answer1 = models.CharField(max_length=200, null=True)
    answer2 = models.CharField(max_length=200, null=True)
    answer3 = models.CharField(max_length=200, null=True)
    answer4 = models.CharField(max_length=200, null=True)
    correct = models.CharField(max_length=2)
    explanation = models.TextField(null=True, blank=True)

class QuestionsMath1(models.Model):
    number = models.IntegerField(null=True)
    paragraph = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    question = models.CharField(max_length=500, null=True)
    answer1 = models.CharField(max_length=200, null=True)
    answer2 = models.CharField(max_length=200, null=True)
    answer3 = models.CharField(max_length=200, null=True)
    answer4 = models.CharField(max_length=200, null=True)
    correct = models.CharField(max_length=2)
    explanation = models.TextField(null=True, blank=True)

class Friendship(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friendship')
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend_of')
    accepted = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pictures', default='noavatar.jpg')
    name = models.CharField(max_length=20, null=True, blank=True)
    math_score = models.IntegerField(null=True, blank=True)
    verbal_score = models.IntegerField(null=True, blank=True)
    tokens = models.IntegerField(null=True, blank=True)
    numberoftest = models.IntegerField(null=True, default=0)

webapp/forms.py
from django import forms



class TestForm(forms.Form):
    question_1 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_2 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_3 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_4 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_5 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_6 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_7 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_8 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_9 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_10 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_11 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_12 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_13 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])
    question_14 = forms.ChoiceField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])

    # Add similar choice fields for all questions

webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from .models import Questions, Friendship, UserProfile, QuestionsVerbal1, QuestionsVerbal3, QuestionsMath1, QuestionsVerbal2
from django.db.models import Q


@login_required
def friends(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)

    friend_requests = Friendship.objects.filter(friend=request.user, accepted=False)
    friends = Friendship.objects.filter(Q(user=request.user) | Q(friend=request.user), accepted=True)

    if request.method == 'POST':
        friend_username = request.POST.get('friend_username')
        friend = User.objects.filter(username=friend_username).first()

        if friend:
            friendship_request = Friendship.objects.filter(user=request.user, friend=friend).first()

            if not friendship_request:
                friendship = Friendship(user=request.user, friend=friend)
                friendship.save()

    return render(request, 'friends.html', {'friend_requests': friend_requests, 'friends': friends, 'user_profile':user_profile})

@login_required
def send_friend_request(request, username):
    friend = get_object_or_404(User, username=username)
    friendship, created = Friendship.objects.get_or_create(user=request.user, friend=friend)
    return redirect('myprofile')

@login_required
def accept_friend_request(request, friendship_id):
    friendship = get_object_or_404(Friendship, id=friendship_id, friend=request.user, accepted=False)
    friendship.accepted = True
    friendship.save()
    return redirect('myprofile')

@login_required()
def payment(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)
    users = User.objects.all()
    if request.method == "POST":
        user_id = request.POST.get('user_id')
        user = User.objects.get(id=user_id)
        user.is_staff = True
        user.save()
        return redirect('myprofile')
    else:
        users = User.objects.all()
        return render(request, 'payment.html', {'users': users, 'user_profile':user_profile})

@login_required()
def test(request):
    questions = Questions.objects.all()

    user_profile = UserProfile.objects.get(user=request.user)
    user_profile.math_score = 0
    user_profile.verbal_score = 0
    user_profile.save()

    if request.method == 'POST':

        answers = []
        corrects = []
        for i in range(1, 15):
            question_1 = Questions.objects.get(number=i)
            correct_answer = question_1.correct
            corrects.append(correct_answer)

            answer1 = request.POST[f'answer{i}']
            answers.append(answer1)

        for j in range(1, 9):
            if answers[j-1] == corrects[j-1]:
                user_profile.verbal_score += 100
                user_profile.tokens += 100
                user_profile.save()

        for j in range(9, 15):
            if answers[j-1] == corrects[j-1]:
                user_profile.math_score += 114
                user_profile.tokens += 114
                user_profile.save()

        if user_profile.math_score > 100 and user_profile.verbal_score > 100:
            user_profile.numberoftest += 1
            user_profile.save()

        if request.user.is_staff:
            condition = 'sui'
            context = {'questions': questions, 'user_profile': user_profile, 'condition': condition}
            return render(request, 'test.html', context)
        else:
            return redirect('myprofile')

    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)

    context = {'questions':questions, 'user_profile': user_profile}

    return render(request, 'test.html', context)



@login_required()
def satverbaltest1(request):
    questions = QuestionsVerbal1.objects.all()

    user_profile = UserProfile.objects.get(user=request.user)
    user_profile.verbal_score = 0
    user_profile.save()

    if request.method == 'POST':

        answers = []
        corrects = []
        for i in range(1, 5):
            question_1 = QuestionsVerbal1.objects.get(number=i)
            correct_answer = question_1.correct
            corrects.append(correct_answer)

            answer1 = request.POST[f'answer{i}']
            answers.append(answer1)

        for j in range(1, 5):
            if answers[j-1] == corrects[j-1]:
                user_profile.verbal_score += 300
                user_profile.tokens += 300
                user_profile.save()

        if user_profile.verbal_score > 100:
            user_profile.numberoftest += 1
            user_profile.save()

        if request.user.is_staff:
            condition = 'sui'
            context = {'questions': questions, 'user_profile': user_profile, 'condition': condition}
            return render(request, 'satverbaltest1.html', context)
        else:
            return redirect('myprofile')

    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)

    context = {'questions':questions, 'user_profile': user_profile}

    return render(request, 'satverbaltest1.html', context)

@login_required()
def satverbaltest2(request):
    questions = QuestionsVerbal2.objects.all()

    user_profile = UserProfile.objects.get(user=request.user)
    user_profile.verbal_score = 0
    user_profile.save()

    if request.method == 'POST':

        answers = []
        corrects = []
        for i in range(1, 5):
            question_1 = QuestionsVerbal2.objects.get(number=i)
            correct_answer = question_1.correct
            corrects.append(correct_answer)

            answer1 = request.POST[f'answer{i}']
            answers.append(answer1)

        for j in range(1, 5):
            if answers[j-1] == corrects[j-1]:
                user_profile.verbal_score += 300
                user_profile.tokens += 300
                user_profile.save()

        if user_profile.verbal_score > 100:
            user_profile.numberoftest += 1
            user_profile.save()

        if request.user.is_staff:
            condition = 'sui'
            context = {'questions': questions, 'user_profile': user_profile, 'condition': condition}
            return render(request, 'satverbaltest2.html', context)
        else:
            return redirect('myprofile')

    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)

    context = {'questions':questions, 'user_profile': user_profile}

    return render(request, 'satverbaltest2.html', context)

@login_required()
def satmathtest1(request):
    questions = QuestionsMath1.objects.all()

    user_profile = UserProfile.objects.get(user=request.user)
    user_profile.math_score = 0
    user_profile.save()

    if request.method == 'POST':

        answers = []
        corrects = []
        for i in range(1, 4):
            question_1 = QuestionsMath1.objects.get(number=i)
            correct_answer = question_1.correct
            corrects.append(correct_answer)

            answer1 = request.POST[f'answer{i}']
            answers.append(answer1)

        for j in range(1, 4):
            if answers[j-1] == corrects[j-1]:
                user_profile.math_score += 375
                user_profile.tokens += 375
                user_profile.save()

        if user_profile.math_score > 100:
            user_profile.numberoftest += 1
            user_profile.save()

        if request.user.is_staff:
            condition = 'sui'
            context = {'questions': questions, 'user_profile': user_profile, 'condition': condition}
            return render(request, 'satmathtest1.html', context)
        else:
            return redirect('myprofile')

    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)

    context = {'questions':questions, 'user_profile': user_profile}

    return render(request, 'satmathtest1.html', context)


@login_required()
def satmath(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)
    context = {'user_profile': user_profile}
    return render(request, 'satmath.html', context)

@login_required()
def satverbal(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)
    context = {'user_profile': user_profile}
    return render(request, 'satverbal.html', context)



@login_required()
def leaderboard(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)



webapp/templates/friends.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/friends.css' %}">
	<title>Friends | ExamBusters</title>
    <link rel="icon" href="{% static 'photos/sat111.jpeg' %}">
        <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation:wght@600&family=Montserrat&family=Oxygen&family=Roboto+Condensed&display=swap" rel="stylesheet">
</head>
<body>

        <nav>
            <a href="#" class="logo">
            {% if user_profile.profile_picture %}
                <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
            {% endif %}
            {% if user_profile.name %}
                <span class="nav-item" alt="">{{ user_profile.name }}</span>
            {% else %}
                <span class="nav-item" alt="">{{ request.user.username }}</span>
            {% endif %}
            </a>
            <a href="{% url 'myprofile' %}" ><img src="{% static 'photos/user.png' %}"  class="logo2" alt="">
            <i class="fas fa-profile"></i>
            <span class="nav-item">My Profile</span>
            </a>
            <a href="{% url 'store' %}"><img src="{% static 'photos/shop.png' %}"  class="logo2" alt="">
            <i class="fas fa-leaderboard "></i>
            <span class="nav-item">Store</span>
            </a>
            <a href="{% url 'leaderboard' %}" ><img src="{% static 'photos/podium.png' %}"  class="logo2" alt="">
            <i class="fas fa-leaderboard "></i>
            <span class="nav-item">Leaderboard</span>
            </a>
            <a href="{% url 'satverbal' %}"><img src="{% static 'photos/chat.png' %}"  class="logo2" alt="">
            <i class="fas fa-Verbal"></i>
            <span class="nav-item">SAT Verbal</span>
            </a>
            <a href="{% url 'satmath' %}"><img src="{% static 'photos/keys.png' %}"  class="logo2" alt="">
            <i class="fas fa-Math"></i>
            <span class="nav-item">SAT Math</span>
            </a>
            <a href="{% url 'friends_list' %}"><img src="{% static 'photos/friends.png' %}"  class="logo2" alt="">
            <i class="fas fa-friends"></i>
            <span class="nav-item">My Friends</span>
            </a>
            <a href="{% url 'payment' %}"><img src="{% static 'photos/payment.png' %}"  class="logo2" alt="">
            <i class="fas fa-chart-payment"></i>
            <span class="nav-item">Payment</span>
            </a>
            <a href="#"><img src="{% static 'photos/quest.png' %}"  class="logo2" alt="">
            <i class="fas fa-quests"></i>
            <span class="nav-item">Daily Quests</span>
            </a>
            <form method="post" action="{% url 'logoutsystem' %}">
                {% csrf_token %}
                <a href="#"><img src="{% static 'photos/logout.png' %}"  class="logo2" alt="">
                <i class="fas fa-sign-out-alt"></i>
                <button type="submit">Logout</button>
                </a>
            </form>
        </nav>
        <div class="container">
        <h1>Friend Requests</h1>
    <ul>
        {% for friend_request in friend_requests %}
            <li>{{ friend_request.user.username }} wants to be your friend! <a href="{% url 'accept_friend_request' friendship_id=friend_request.id %}">Accept</a></li>
        {% empty %}
            <li>No friend requests.</li>
        {% endfor %}
    </ul>

    <h1>Friends</h1>
    <ul>
        {% for friendship in friends %}
            {% if friendship.user == user %}
                <li>{{ friendship.friend.username }}</li>
            {% else %}
                <li>{{ friendship.user.username }}</li>
            {% endif %}
        {% empty %}
            <li>No friends yet.</li>
        {% endfor %}
    </ul>

    <h1>Add a Friend</h1>
    <form method="post">
        {% csrf_token %}
        <label for="friend_username">Friend's Username:</label>
        <input type="text" id="friend_username" name="friend_username">
        <button type="submit">Send Friend Request</button>
    </form>
</div>
</body>
</html>

webapp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login | ExamBusters</title>
    <link rel="stylesheet" href="{% static 'css/login1.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation:wght@600&family=Montserrat&family=Oxygen&family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="icon" href="{% static 'photos/sat111.jpeg' %}">
<body>
  <div class="login-box">
      <h2>Login</h2>
      <form method="POST" action="{% url 'loginsystem' %}">
          {% csrf_token %}
        <div class="user-box">
          <input type="text" name="username" required="">
          <label>Username</label>
        </div>
        <div class="user-box">
          <input type="password" name="password" required="">
          <label>Password</label>
        </div>
          <div class="incorrect-password">
            <p>{{ error }}</p>
          </div>
        <button type="submit">Login
        </button>
        <div class="signup-link">Don't have an account? <a href="{% url 'signupsystem' %}">Signup</a></div>
      </form>
  </div>
</body>
</html>


webapp/templates/myprofile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My Profile | ExamBusters</title>
    <link rel="icon" href="{% static 'photos/sat111.jpeg' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation:wght@600&family=Montserrat&family=Oxygen&family=Roboto+Condensed&display=swap" rel="stylesheet">
</head>
<body>
  <div class="container">
    <nav>
            <a href="#" class="logo">
            {% if user_profile.profile_picture %}
                <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
            {% endif %}
            {% if user_profile.name %}
                <span class="nav-item" alt="">{{ user_profile.name }}</span>
            {% else %}
                <span class="nav-item" alt="">{{ request.user.username }}</span>
            {% endif %}
            </a>
            <a href="{% url 'myprofile' %}" ><img src="{% static 'photos/user.png' %}"  class="logo2" alt="">
            <i class="fas fa-profile"></i>
            <span class="nav-item">My Profile</span>
            </a>
            <a href="{% url 'store' %}"><img src="{% static 'photos/shop.png' %}"  class="logo2" alt="">
            <i class="fas fa-leaderboard "></i>
            <span class="nav-item">Store</span>
            </a>
            <a href="{% url 'leaderboard' %}" ><img src="{% static 'photos/podium.png' %}"  class="logo2" alt="">
            <i class="fas fa-leaderboard "></i>
            <span class="nav-item">Leaderboard</span>
            </a>
            <a href="{% url 'satverbal' %}"><img src="{% static 'photos/chat.png' %}"  class="logo2" alt="">
            <i class="fas fa-Verbal"></i>
            <span class="nav-item">SAT Verbal</span>
            </a>
            <a href="{% url 'satmath' %}"><img src="{% static 'photos/keys.png' %}"  class="logo2" alt="">
            <i class="fas fa-Math"></i>
            <span class="nav-item">SAT Math</span>
            </a>
            <a href="{% url 'friends_list' %}"><img src="{% static 'photos/friends.png' %}"  class="logo2" alt="">
            <i class="fas fa-friends"></i>
            <span class="nav-item">My Friends</span>
            </a>
            <a href="{% url 'payment' %}"><img src="{% static 'photos/payment.png' %}"  class="logo2" alt="">
            <i class="fas fa-chart-payment"></i>
            <span class="nav-item">Payment</span>
            </a>
            <a href="{% url 'satverbaltest2' %}"><img src="{% static 'photos/quest.png' %}"  class="logo2" alt="">
            <i class="fas fa-quests"></i>
            <span class="nav-item">Daily Quests</span>
            </a>
            <form method="post" action="{% url 'logoutsystem' %}">
                {% csrf_token %}
                <a href="#"><img src="{% static 'photos/logout.png' %}"  class="logo2" alt="">
                <i class="fas fa-sign-out-alt"></i>
                <button type="submit">Logout</button>
                </a>
            </form>
        </nav>
    <div class="content">
        {% if user_profile.name %}
                <h1 class="username">{{ user_profile.name }}</h1>
            {% else %}
                <h1 class="username">{{ request.user.username }}</h1>
            {% endif %}
        <h2>Scores of the LAST tests:</h2>
        <br>
      <div class="score">
        <div class="subject">
          <div class="bar">
            <div class="fill fill-math"></div>
          </div>
          <span class="score-value math-score">{{ user_profile.math_score }}</span>
        </div>
        <div class="subject">
          <div class="bar">
            <div class="fill fill-verbal"></div>
          </div>
          <span class="score-value verbal-score">{{ user_profile.verbal_score }}</span>
        </div>
        <div class="subject">
          <div class="bar">
            <div class="fill fill-total"></div>
          </div>
          <span class="score-value superscore">{{ superscore }}</span>
        </div>
      </div>
      <div class="tokens">
        <h2>Tokens:</h2>
        <span class="token-count">{{ user_profile.tokens }}</span>
      </div>
        <br><br><br><br>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_profile_picture">Profile Picture:</label>
        <input type="file" name="profile_picture" id="id_profile_picture">
        <br>
        <label for="id_username">Name:</label>
        <input type="text" name="name" id="id_username">
        <br>
        <input type="submit" value="Save">
      </form>
    </div>
  </div>

  <script>
    const mathScore = document.querySelector(".math-score");
    const verbalScore = document.querySelector(".verbal-score");
    const superscore = document.querySelector(".superscore");
    const mathBar = document.querySelector(".fill-math");
    const verbalBar = document.querySelector(".fill-verbal");
    const totalBar = document.querySelector(".fill-total");
    const mathScoreValue = parseInt(mathScore.innerHTML);
    const verbalScoreValue = parseInt(verbalScore.innerHTML);
    const superscoreValue = parseInt(superscore.innerHTML);
    const totalScore = mathScoreValue + verbalScoreValue;

    mathBar.style.width = (mathScoreValue / 800) * 100 + "%";
    verbalBar.style.width = (verbalScoreValue / 800) * 100 + "%";
    totalBar.style.width = (superscoreValue / 1600) * 100 + "%";
    mathScore.innerHTML = "Math: " + mathScoreValue;
    verbalScore.innerHTML = "Verbal: " + verbalScoreValue;
    superscore.innerHTML = "Total: " + superscoreValue;

    mathScore.animate([{ score: 0 }, { score: mathScoreValue }], {
      duration: 1000,
      easing: "ease-out",
      fill: "forwards",
    });

    verbalScore.animate([{ score: 0 }, { score: verbalScoreValue }], {
      duration: 1000,
      easing: "ease-out",
      fill: "forwards",
    });

    superscore.animate([{ score: 0 }, { score: totalScore }], {
      duration: 1000,
      easing: "ease-out",
      fill: "forwards",
    });
  </script>
</body>
</html>


webapp/templates/signupsystem.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SignUp| ExamBusters</title>
    <link rel="icon" href="{% static 'photos/sat111.jpeg' %}">
    <link rel="stylesheet" href="{% static 'css/login1.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation:wght@600&family=Montserrat&family=Oxygen&family=Roboto+Condensed&display=swap" rel="stylesheet">
<body>
  <div class="login-box">
      {% csrf_token %}
      <h2>SignUp</h2>
      <form method="POST" action="{% url 'signupsystem' %}">
          {% csrf_token %}
        <div class="user-box">
          <input type="text" name="username" required="">
          <label>Username</label>
        </div>
        <div class="user-box">
          <input type="password" name="password1" required="">
          <label>Password</label>
        </div>
          <div class="user-box">
          <input type="password" name="password2" required="">
          <label>Password Again</label>
        </div>
          <div class="incorrect-password">
            <p>{{ error }}</p>
          </div>
        <button type="submit">SignUp
        </button>
        <div class="signup-link">Already have an account? <a href="{% url 'loginsystem' %}">Login</a></div>
      </form>
  </div>
</body>
</html>
